export interface Users {
    uid: string; // generated by firebase
    role: 'employee' | 'admin';
    name: string;
    email: string; // filtered to be @innbucks.co.zw
    id: string;
    hireDate: Date;
    esig?: any;
}


// Test users
export const testUsers: Users[] = [
  {
    uid: 'UID001',
    role: 'admin',
    name: 'Tawanda Chikomo',
    email: 'tawanda.chikomo@innbucks.co.zw',
    id: 'EMP1001',
    hireDate: new Date('2022-06-12'),
    esig: {
      initials: 'TC'
    }
  },
  {
    uid: 'UID002',
    role: 'employee',
    name: 'Linda Mupfudza',
    email: 'linda.mupfudza@innbucks.co.zw',
    id: 'EMP1002',
    hireDate: new Date('2023-02-28'),
    esig: null
  },
  {
    uid: 'UID003',
    role: 'employee',
    name: 'Kudzai Nyathi',
    email: 'kudzai.nyathi@innbucks.co.zw',
    id: 'EMP1003',
    hireDate: new Date('2024-08-01'),
    esig: {
      imageUrl: 'https://example.com/esig/kudzai.png'
    }
  },
  {
    uid: 'UID004',
    role: 'admin',
    name: 'Rudo Makoni',
    email: 'rudo.makoni@innbucks.co.zw',
    id: 'EMP1004',
    hireDate: new Date('2021-12-05'),
    esig: {
      initials: 'RM'
    }
  },
  {
    uid: 'UID005',
    role: 'employee',
    name: 'Tapiwa Zulu',
    email: 'tapiwa.zulu@innbucks.co.zw',
    id: 'EMP1005',
    hireDate: new Date('2023-09-19'),
    esig: null
  }
];